models.clip.weight_path: '~/models/clip_reid/csu_f0_eitc.pth'
models.clip.vocab_path: '~/models/clip_reid/bpe_simple_vocab_16e6.txt.gz'
models.pstr.config_path: './configs/pstr/tdbaseline.py'
models.pstr.weight_path: '~/models/pstr_OG/pstr_r50_cuhk_origin.pth'

process.tokens_batch_size: 512
process.crops_batch_size: 256
process.frames_batch_size: 3
process.num_workers: 2

eval.alpha: .5
eval.threshold: .25

data.root_folder: '~/data/csu3'
data.annotations: '~/data/csu3/annotations/test.parquet'
data.annotations_json: './outputs/test.json'
data.frames_folder: '~/data/csu3/test'
data.crops_folder: '~/data/csu3/crops'

h5_files.crop_features_from_annotations: './outputs/crop-index_to_crop_features_from_annotations.h5'
h5_files.crop_features_from_detections: './outputs/frame-id_to_crop_features_from_detections.h5'
h5_files.crop_features_from_files: './outputs/crop-index_to_crop_features_from_files.h5'
h5_files.detections: './outputs/frame-id_to_detections.h5'
h5_files.features_text: './outputs/crop-index_to_features_text.h5'
